In [1]:
%cd ../..

/nfs/homedirs/fuchsgru/MastersThesis


In [4]:
import gust
import numpy as np
import matplotlib.pyplot as plt
import scipy.sparse as sp
from sklearn.feature_extraction.text import TfidfVectorizer
from data.base import SingleGraphDataset
from data.npz import NpzDataset
import data.util
import os.path as osp
from util import sparse_max

In [5]:
npz_dat = NpzDataset('cora_full', 
                    )

In [14]:
gust_dat = gust.datasets.load_dataset('cora_ml').standardize(select_lcc=True)
gust_dat

<Undirected, unweighted and connected SparseGraph with 15962 edges (no self-loops). Data: adj_matrix (2810x2810), attr_matrix (2810x2879), labels (2810), node_names (2810), attr_names (2879), class_names (7)>

In [12]:
npz_dat[0].x.shape

torch.Size([18800, 8704])

In [8]:
gust_dat

<Undirected, unweighted and connected SparseGraph with 125370 edges (no self-loops). Data: adj_matrix (18800x18800), attr_matrix (18800x8710), labels (18800), node_names (18800), attr_names (8710), class_names (70)>

In [9]:
set(ds2[0].feature_to_idx).issubset(set(ds3[0].feature_to_idx))

True

In [49]:
arr['labels']

array([ 0,  0,  0, ..., 52, 59, 55])

In [48]:
arr['idx_to_class'].item()

{0: 'Information_Retrieval/Retrieval',
 1: 'Information_Retrieval/Filtering',
 2: 'Databases/Object_Oriented',
 3: 'Artificial_Intelligence/Machine_Learning/Case-Based',
 4: 'Information_Retrieval/Extraction',
 5: 'Artificial_Intelligence/NLP',
 6: 'Encryption_and_Compression/Encryption',
 7: 'Operating_Systems/Distributed',
 8: 'Artificial_Intelligence/Data_Mining',
 9: 'Artificial_Intelligence/Speech',
 10: 'Databases/Query_Evaluation',
 11: 'Artificial_Intelligence/Knowledge_Representation',
 12: 'Information_Retrieval/Digital_Library',
 13: 'Networking/Protocols',
 14: 'Artificial_Intelligence/Theorem_Proving',
 15: 'Encryption_and_Compression/Security',
 16: 'Networking/Wireless',
 17: 'Hardware_and_Architecture/Memory_Structures',
 18: 'Data_Structures__Algorithms_and_Theory/Quantum_Computing',
 19: 'Data_Structures__Algorithms_and_Theory/Computational_Complexity',
 20: 'Artificial_Intelligence/Machine_Learning/Theory',
 21: 'Data_Structures__Algorithms_and_Theory/Computational_G

In [24]:
arr = np.load('data/raw/cora.npz', allow_pickle=True)

In [38]:
arr['idx_to_node'].item()

{0: '19826\n',
 1: '1152506\n',
 2: '1152594\n',
 3: '1121282\n',
 4: '1153684\n',
 5: '1152952\n',
 6: '4527\n',
 7: '22112\n',
 8: '33991\n',
 9: '98029\n',
 10: '138991\n',
 11: '249849\n',
 12: '5050\n',
 13: '577487\n',
 14: '520640\n',
 15: '29459\n',
 16: '1103471\n',
 17: '181487\n',
 18: '29460\n',
 19: '1108185\n',
 20: '1108525\n',
 21: '1152637\n',
 22: '521840\n',
 23: '186019\n',
 24: '29470\n',
 25: '1134753\n',
 26: '18452\n',
 27: '129558\n',
 28: '23449\n',
 29: '282\n',
 30: '3286\n',
 31: '3516\n',
 32: '19913\n',
 33: '4518\n',
 34: '6840\n',
 35: '9086\n',
 36: '16217\n',
 37: '11036\n',
 38: '16917\n',
 39: '12956\n',
 40: '24023\n',
 41: '24046\n',
 42: '20373\n',
 43: '34897\n',
 44: '39450\n',
 45: '40735\n',
 46: '19896\n',
 47: '47400\n',
 48: '88348\n',
 49: '100336\n',
 50: '1106310\n',
 51: '101929\n',
 52: '844031\n',
 53: '103548\n',
 54: '103551\n',
 55: '18447\n',
 56: '104438\n',
 57: '106531\n',
 58: '107173\n',
 59: '107176\n',
 60: '310839\n',
 61

In [28]:
list(arr.keys())

['adj_indptr',
 'adj_indices',
 'attr_indices',
 'adj_shape',
 'attr_shape',
 'idx_to_node',
 'idx_to_attr',
 'adj_data',
 'labels',
 'attr_data',
 'attr_indptr',
 'attr_text',
 'idx_to_class']

In [7]:
A = sp.csr_matrix((arr['adj_data'], arr['adj_indices'], arr['adj_indptr']), shape=arr['adj_shape'])
X = sp.csr_matrix((arr['attr_data'], arr['attr_indices'], arr['attr_indptr']), shape=arr['attr_shape'])

In [8]:
neq = (A != A.T)

In [13]:
neq.data.sum() / neq.data.shape

array([1.])

In [53]:
raw_text = arr['attr_text']
raw_text.shape

(19793,)

In [73]:
vectorizer = TfidfVectorizer(min_df=10)
X_new = vectorizer.fit_transform(raw_text)

In [74]:
X.shape, X_new.shape

((19793, 8710), (19793, 8977))

In [43]:
arr['attr_indptr'].shape, arr['attr_indptr'].max()

((19794,), 1125610)

In [35]:
arr['adj_indices'].shape, arr['adj_indices'].max()

((65311,), 19792)

In [36]:
arr['adj_shape']

array([19793, 19793])

In [37]:
arr['attr_shape']

array([19793,  8710])

In [38]:
arr['adj_data'].shape

(65311,)

In [39]:
arr['attr_text'][0]

'With the vast number of information resources available today, a critical problem is how to locate, retrieve and process information. It would be impractical to build a single unified system that combines all of these information resources. A more promising approach is to build specialized information retrieval agents that provide access to a subset of the information resources and can send requests to other information retrieval agents when appropriate. In this paper we present the architecture of the individual information retrieval agents and describe how this architecture supports a network of cooperating information agents. We describe how these information agents represent their knowledge, communicate with other agents, dynamically construct information retrieval plans, and learn about other agents to improve efficiency. We have already built a small network of agents that have these capabilities and provide access to information for transportation planning.'

In [40]:
arr['idx_to_class']

array({0: 'Information_Retrieval/Retrieval', 1: 'Information_Retrieval/Filtering', 2: 'Databases/Object_Oriented', 3: 'Artificial_Intelligence/Machine_Learning/Case-Based', 4: 'Information_Retrieval/Extraction', 5: 'Artificial_Intelligence/NLP', 6: 'Encryption_and_Compression/Encryption', 7: 'Operating_Systems/Distributed', 8: 'Artificial_Intelligence/Data_Mining', 9: 'Artificial_Intelligence/Speech', 10: 'Databases/Query_Evaluation', 11: 'Artificial_Intelligence/Knowledge_Representation', 12: 'Information_Retrieval/Digital_Library', 13: 'Networking/Protocols', 14: 'Artificial_Intelligence/Theorem_Proving', 15: 'Encryption_and_Compression/Security', 16: 'Networking/Wireless', 17: 'Hardware_and_Architecture/Memory_Structures', 18: 'Data_Structures__Algorithms_and_Theory/Quantum_Computing', 19: 'Data_Structures__Algorithms_and_Theory/Computational_Complexity', 20: 'Artificial_Intelligence/Machine_Learning/Theory', 21: 'Data_Structures__Algorithms_and_Theory/Computational_Geometry', 22: '